### ISSUE TITLE
List of unique items for filter generation

### ISSUE THREAD

**Issue by Xeverous** [lvlvllvlvllvlvl/RePoE#1]
Context (read this first please): https://old.reddit.com/r/pathofexiledev/comments/18wppb1/how_to_reliably_obtain_names_and_bases_of_all/

I got a link to https://lvlvllvlvllvlvl.github.io/RePoE/uniques_poewiki.json which is a great resource, however I still got few small problems to solve and would like to ask for some guidance:

- The `docs` folder has no description file for unique items - most fields are trivial to understand but being sure something works in specific way will help.
- One of the fields in uniques is `is_drop_restricted` which (if `1`) unfortunately bundles together boss-only uniques with vendor-exclusive uniques (e.g. Loreweave). Filters don't care about vendor-exclusive uniques so I need to get or make a separate list for it. Can this be automated or is there is an automated list of vendor-exclusive uniques? PoB has "Source: Vendor Recipe" somehow in its uniques.
- There are other problems with aggressive unique item filtering (such as still wanting to pickup Ventor's Gamble even if poe.ninja says it's just few chaos) but this will likely require manual, individual item analysis and AFAIK RePoE can't help me with it.

**Comment by lvlvllvlvllvlvl** [comment]
hi, sorry for the delay. l have gone back to work and haven't had a chance to look at this yet but l haven't forgotten about it

**Comment by lvlvllvlvllvlvl** [comment]
Hi, l have taken a look and unfortunately it doesn't look like the information you want is available from the wiki. GGG don't publish drop locations or vendor recipes or make them available in the game files, they need to be discovered by players and are maintained by hand in the wiki - the 'drop_text' and 'drop_monsters' fields are enough for the wiki's purposes but l don't think they can be machine-parsed to provide the data you want.

Documentation for the wiki data fields is available on the wiki at https://www.poewiki.net/wiki/Template:Base_item

**Comment by Xeverous** [comment]
Now I apologize for the late reply;

So if I understood correctly, various fields in the item template are hand-written and any automation applied to such hand-written fields is risky...

Well, in that case I can only rely on datamined information and all kinds of special items (like vendor-only unique or card-only unique) will have to be handpicked aswell, just like the wiki does it manually.
